"""empty message

Revision ID: 0402bd5b0d3c
Revises: 4727e5aa5c8e
Create Date: 2024-06-13 14:54:38.287667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0402bd5b0d3c'
down_revision = '4727e5aa5c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('send_user_id', sa.Integer(), nullable=False),
    sa.Column('receiver_user_id', sa.Integer(), nullable=False),
    sa.Column('chat_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['send_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('follow',
    sa.Column('follow_id', sa.Integer(), nullable=False),
    sa.Column('follower_user_id', sa.Integer(), nullable=False),
    sa.Column('followed_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['follower_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('follow_id')
    )
    op.create_table('moyamoya',
    sa.Column('moyamoya_id', sa.Integer(), nullable=False),
    sa.Column('moyamoya_post', sa.String(length=255), nullable=False),
    sa.Column('post_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('moyamoya_id')
    )
    op.create_table('pots',
    sa.Column('pots_id', sa.Integer(), nullable=False),
    sa.Column('audio_file', sa.String(length=255), nullable=False),
    sa.Column('emotion_score', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('stress_level', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pots_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pots_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('pots_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pots')
    op.drop_table('moyamoya')
    op.drop_table('follow')
    op.drop_table('chats')
    # ### end Alembic commands ###
