"""empty message

Revision ID: 05623b9fab4f
Revises: 224719727ff8
Create Date: 2025-01-19 22:52:50.480770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05623b9fab4f'
down_revision = '224719727ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_session',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('caller_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caller_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group_chat.group_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('call_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['call_session.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_participants')
    op.drop_table('call_session')
    # ### end Alembic commands ###
