"""empty message

Revision ID: 0a5c429ff061
Revises: 7da9dfd8234c
Create Date: 2024-10-14 22:48:49.379084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5c429ff061'
down_revision = '7da9dfd8234c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_chat',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('group_member',
    sa.Column('group_member_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_chat.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('group_member_id')
    )
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.alter_column('receiver_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'group_chat', ['group_id'], ['group_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('receiver_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('group_id')

    op.drop_table('group_member')
    op.drop_table('group_chat')
    # ### end Alembic commands ###
