"""empty message

Revision ID: 188bc1f08c01
Revises: c3935cb50fe9
Create Date: 2024-11-11 21:59:00.501956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188bc1f08c01'
down_revision = 'c3935cb50fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classification', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pots', schema=None) as batch_op:
        batch_op.drop_column('classification')

    # ### end Alembic commands ###
