"""empty message

Revision ID: 1c2552915735
Revises: 3d325f2ca82d
Create Date: 2024-08-27 21:46:44.868372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c2552915735'
down_revision = '3d325f2ca82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nice', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_post_like', ['post_id', 'user_id'])
        batch_op.drop_column('count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('unique_user_post_like', type_='unique')

    # ### end Alembic commands ###
