"""empty message

Revision ID: 3d325f2ca82d
Revises: bf9755660c10
Create Date: 2024-08-25 23:02:54.177342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d325f2ca82d'
down_revision = 'bf9755660c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nice',
    sa.Column('nice_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['moyamoya.moyamoya_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('nice_id')
    )
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_friendship', ['follower_user_id', 'followed_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_constraint('unique_friendship', type_='unique')

    op.drop_table('nice')
    # ### end Alembic commands ###
