"""empty message

Revision ID: 42180c32f282
Revises: 
Create Date: 2024-09-14 16:26:49.521246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42180c32f282'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('e_mail', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('prof_image', sa.String(length=255), nullable=True),
    sa.Column('second_image', sa.String(length=255), nullable=True),
    sa.Column('prof_comment', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('chats',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('send_user_id', sa.Integer(), nullable=False),
    sa.Column('receiver_user_id', sa.Integer(), nullable=False),
    sa.Column('chat_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['send_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('follow',
    sa.Column('follow_id', sa.Integer(), nullable=False),
    sa.Column('follower_user_id', sa.Integer(), nullable=False),
    sa.Column('followed_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['follower_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('follow_id'),
    sa.UniqueConstraint('follower_user_id', 'followed_user_id', name='unique_friendship')
    )
    op.create_table('moyamoya',
    sa.Column('moyamoya_id', sa.Integer(), nullable=False),
    sa.Column('moyamoya_post', sa.String(length=255), nullable=False),
    sa.Column('post_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('moyamoya_id')
    )
    op.create_table('pots',
    sa.Column('pots_id', sa.Integer(), nullable=False),
    sa.Column('audio_file', sa.String(length=255), nullable=False),
    sa.Column('emotion_score', sa.Float(), nullable=True),
    sa.Column('stress_level', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pots_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pots_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('pots_id')
    )
    op.create_table('bookmark',
    sa.Column('bookmark_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['moyamoya.moyamoya_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('bookmark_id')
    )
    op.create_table('nice',
    sa.Column('nice_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['moyamoya.moyamoya_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('nice_id'),
    sa.UniqueConstraint('post_id', 'user_id', name='unique_user_post_like')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nice')
    op.drop_table('bookmark')
    op.drop_table('pots')
    op.drop_table('moyamoya')
    op.drop_table('follow')
    op.drop_table('chats')
    op.drop_table('user')
    # ### end Alembic commands ###
