"""empty message

Revision ID: cd70ec72ff11
Revises: 05623b9fab4f
Create Date: 2025-03-08 23:20:06.278662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd70ec72ff11'
down_revision = '05623b9fab4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pots', schema=None) as batch_op:
        batch_op.alter_column('solution',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pots', schema=None) as batch_op:
        batch_op.alter_column('solution',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
