"""empty message

Revision ID: f795aad761de
Revises: 42180c32f282
Create Date: 2024-09-26 22:53:08.116983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f795aad761de'
down_revision = '42180c32f282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moyamoya', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_tag', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moyamoya', schema=None) as batch_op:
        batch_op.drop_column('hash_tag')

    # ### end Alembic commands ###
